name: .NET

on:
  push:
    tags:
      - "v*.*.*"
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.400' 
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test with the dotnet CLI
        run: dotnet test
        
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
